# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2f9c8b73e26a6a0f36699887cdad12275cfad6a949ff8478607b4cbf082f4468e49159ea8d74990b761b7ca2419095ca493d3aafb30c2b976ad7b3ee6cd88841

test:
  secret_key_base: a2f8941baaa46fa6d8f20db3e6e959364610e692f71a1e86f6becd3a926d936e9095d2177f2086fbc855f18e81f14b01d6f453315c347b42d068a3c57ebf4603

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
